### ISSUE TITLE
mongod로 안하고 docker로 mongo를 띄우면 장점이 뭔가요 선생님?

### ISSUE THREAD

**Issue by seriousmac** [yevgnenll/mongo#1]
mongod로 안하고 docker로 mongo를 띄우면 장점이 뭔가요 선생님?

**Comment by yevgnenll** [comment]
docker 로 띄우는 이유는 다음과 같습니다.

1. window 컴에 mongo 를 깔자니 겁남
2. 그래 좋다 깔자 이거야 mongo 를 안쓰면 과연 내가 지울까?
3. 모든 설정이 너무 귀찮...

docker 는 이 부분을 이렇게 해결합니다.

걍 띄워서 쓰고, 안쓰면 docker 이미지를 지우면 됩니다 끄읕!

너무 편하당 ><

**Comment by yevgnenll** [comment]
실제서비스는 설치하긴 해야겠지만 mongo를 사용할지 말지 결정하는 단계라 굳이 그 시간을 사용하지 않아도 될거 같숩네다
